version: "3.5"

services:

  debian:
    build: .
    image: apaskal/javascript-neovim:latest
    container_name: debian-sid
    hostname: debian.a4pi
    ports:
      - "3000:3000"
    networks: 
      - a4pi
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ../devel:/home/app/devel
    working_dir: /home/app/devel
    command: sleep 365d
    logging:
      driver: json-file
      options:
        max-size: 20m

networks:
  a4pi:
    name: "a4pi"
